### PR TITLE
Bug fixed in ftshoeDriver.cpp

### PR DESCRIPTION
**Pull request by InesSorrentino**
Bug fixed in the resulting moment formula

### CODE REVIEW

**Comment by traversaro** [comment]
Good catch!

**Comment by traversaro** [comment]
Can you comment a bit on what was the effect of this bug before the fix? I think it affected several results obtained in the past, thanks!

**Comment by InesSorrentino** [comment]
I'm not sure on how the torques were used in the past, but in my case (I'm using that vector to compute the center of pressure on the shoe), I was having totally wrong results.

The important thing is that for the sensors PRO.02 a different formula was used, because the orientation of the ftsensors was different.

**Comment by traversaro** [comment]
Ok, thanks!

**Comment by traversaro** [comment]
Not sure who the maintainer of the repo is supposed to be (perhaps @fjandrad , but he is busy with the thesis, so I went ahead and I merged the PR).

**Comment by fjandrad** [comment]
Ups yes, I think it was a shared responsibility between me and @lucaTagliapietra , now it should be me. Thanks @traversaro

**Pull request merged**
